version: '3.8'

services:
  web:
    build: ./src
    command: |
      bash -c 'while ! nc -z db 5432;do sleep 1;done;uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://fapi_async_bin:fapi_async_bin@db/fapi_async_bin_dev
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fapi_async_bin
      - POSTGRES_PASSWORD=fapi_async_bin
      - POSTGRES_DB=fapi_async_bin_dev

volumes:
  postgres_data:
